name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2019, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.1
      id: cuda-toolkit
      with:
        cuda: '11.2.2'
        
    - uses: actions/checkout@v1
    
    - name: Build
      working-directory: ${{github.workspace}}
      run: python build.py --build_type ${{env.BUILD_TYPE}}
