name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false # todo set to true when works
      matrix:
        os: [windows-2019, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: Jimver/cuda-toolkit@v0.2.2
        id: cuda-toolkit
        with:
          cuda: "11.2.2"

      - uses: actions/checkout@v2

      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          nvcc --version;
          cmake --version;
          python --version;
          python build.py --build_type ${{env.BUILD_TYPE}};
